name: LaTeX to PDF and JPEG

on:
  push:
    branches:
      - '*'
      - '!main'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ImageMagick
        run: sudo apt-get install -y ghostscript imagemagick texlive-fonts-extra texlive-fonts-recommended texlive-latex-base

      - name: Compile LaTeX to PDF
        if: |
          endsWith(github.event.head_commit.modified, '.tex')
        run: |
          pdflatex cheatsheet.tex

      - name: Change ImageMagick security policy
        if: |
          endsWith(github.event.head_commit.modified, '.tex')
        run: |
          DQT='"'
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

      - name: Convert PDF to JPEG
        run: |
          convert -density 300 -quality 90 cheatsheet.pdf cheatsheet.jpg

      - name: Add and Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cheatsheet.pdf cheatsheet.jpg
          git commit -m "Add cheatsheet.pdf cheatsheet.jpg"
          git push origin ${{ github.ref }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cheatsheet.pdf
          asset_name: cheatsheet.pdf
          asset_content_type: application/pdf

      - name: Upload JPEG to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cheatsheet.jpg
          asset_name: cheatsheet.jpg
          asset_content_type: image/jpeg
